background {
    monitor = eDP-1
    path = /home/nikita/Pictures/wallpapers/wallhaven-5gj5j8_1920x1080.png   # only png supported for now
    color = rgba(25, 20, 20, 1.0)

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 1 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

label {
    monitor = eDP-1
    text = Hi, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 40
    font_family = Hurmit Nerd Font

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 100
    font_family = Hurmit Nerd Font

    position = 0, 100
    halign = center
    valign = center
}

