hl.on("hyprland.start", function()
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("waybar")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("batsignal")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("clipse -listen")
end)
