#!/usr/bin/env sh

if pidof gtklock >/dev/null; then
    exit 1
fi

hyprctl switchxkblayout keyd-virtual-keyboard 0
grim /tmp/lock.jpg
convert -scale 10% -blur 0x2.5 -resize 1000% /tmp/lock.jpg /tmp/lock.jpg
gtklock
