#!/usr/bin/env sh

if pidof gtklock >/dev/null; then
    exit 1
fi

hyprctl switchxkblayout keyd-virtual-keyboard 0
grim /tmp/lock.jpg

convert \
    -scale 5% \
    -fill black -colorize 20 \
    -scale 2000% \
    /tmp/lock.jpg /tmp/lock.jpg
gtklock
