#!/usr/bin/env bash

set -euo pipefail

headphones="alsa_output.usb-BEHRINGER_UMC204HD_192k-00.HiFi__Line1__sink"
speakers="alsa_output.pci-0000_09_00.1.hdmi-stereo"
default_sink=$(wpctl inspect @DEFAULT_AUDIO_SINK@ | grep node.name | awk '{print $NF}' | tr -d '"')

echo $default_sink

set_default_sink() {
    wpctl set-default $(pw-dump | jq ".[] | select(.type==\"PipeWire:Interface:Node\") | select(.info.props.\"media.class\"==\"Audio/Sink\") | .info.props | select(.\"node.name\"==\"$1\") | .\"object.id\"")
}

if [ "$default_sink" = "$headphones" ]; then
    set_default_sink "$speakers"
else
    set_default_sink "$headphones"
fi

