#!/usr/bin/env bash

set -euo pipefail

headphones="alsa_output.usb-BEHRINGER_UMC204HD_192k-00.HiFi__Line1__sink"
speakers="TU106 High Definition Audio Controller Digital Stereo (HDMI)"
default_sink=$(wpctl status | grep Default -A2 | grep Sink | awk '{print $3}')

set_default_sink() {
    wpctl set-default $(wpctl status | grep "$1 " | awk '{print $2}')
}

if [ "$default_sink" = "$headphones" ]; then
    set_default_sink "$speakers"
else
    set_default_sink "$headphones"
fi

