#!/usr/bin/env bash

set -euo pipefail

headphones="alsa_output.usb-BEHRINGER_UMC204HD_192k-00.HiFi__Line1__sink"
speakers="bluez_output.C0_84_7D_C3_D9_1B.1"
speakersBT="C0:84:7D:C3:D9:1B"
earbuds="bluez_output.78_04_E3_30_9D_93.1"
earbudsBT="78:04:E3:30:9D:93"
default_sink=$(wpctl inspect @DEFAULT_AUDIO_SINK@ | grep node.name | awk '{print $NF}' | tr -d '"')

set_default_sink() {
    wpctl set-default $(pw-dump | jq ".[] | select(.type==\"PipeWire:Interface:Node\") | select(.info.props.\"media.class\"==\"Audio/Sink\") | .info.props | select(.\"node.name\"==\"$1\") | .\"object.id\"")
}

is_bt_connected() {
    bluetoothctl info "$1" | grep -q "Connected: yes"
}

connectBT() {
    if is_bt_connected "$1"; then
        set_default_sink "$2"
        return 0
    fi

    bluetoothctl connect "$1"

    for i in {1..5}; do
        if is_bt_connected "$1"; then
            set_default_sink "$2"
            return 0
        fi
        sleep 0.5
    done

    notify-send Bluetooth "Connection to $1 failed"
    return 1
}

if [ "$default_sink" = "$headphones" ]; then
    if is_bt_connected "$earbudsBT"; then
        set_default_sink "$earbuds"
    else
        connectBT "$speakersBT" "$speakers"
    fi
elif [ "$default_sink" = "$speakers" ] && is_bt_connected "$earbudsBT"; then
    set_default_sink "$earbuds"
else
    set_default_sink "$headphones"
fi
