#!/usr/bin/env bash

selected=$({ \
    fd --type directory --follow --hidden --max-depth 1 . \
    ~/Scripts ~/Documents ~/.config ~/Downloads ~/; \ 
    fd --type directory --follow --hidden . \
    ~/Projects; } | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

if [[ -z $TMUX ]]; then
    tmux new-session -c $selected
else
    tmux send-keys "cd $selected" C-m
fi

